USE [master]
GO

/****** Object:  Database [BankingApp]    Script Date: 2023/10/04 12:10:57 ******/
CREATE DATABASE [BankingApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BankingApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BankingApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BankingApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BankingApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BankingApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BankingApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BankingApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BankingApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BankingApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BankingApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [BankingApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BankingApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BankingApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BankingApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BankingApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BankingApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BankingApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BankingApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BankingApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BankingApp] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BankingApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BankingApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BankingApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BankingApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BankingApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BankingApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BankingApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BankingApp] SET RECOVERY FULL 
GO

ALTER DATABASE [BankingApp] SET  MULTI_USER 
GO

ALTER DATABASE [BankingApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BankingApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BankingApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BankingApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BankingApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BankingApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BankingApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BankingApp] SET  READ_WRITE 
GO


